### ISSUE TITLE
1.3.0版本生成报错

### ISSUE THREAD

**Issue by dh224** [ChrAlpha/hexo-theme-cards#101]
一个空的hexo网站，1.3.0版本，会在hexo g的时候报错。使用hexo s --debug看到报错信息是
Unhandled rejection Error: C:\blog\satt\themes\cards\layout\index.ejs:2
    1| <main class="main">
 >> 2|     <%- partial('_partial/post/post-list') %>
    3| </main>
    4|

C:\blog\satt\themes\cards\layout\_partial\post\post-list.ejs:6
    4|             <% page.posts.each((post) => { %>
    5|                 <div class='post-entry content-card'>
 >> 6|                     <%- partial('./post-entry', {post: post}) %>
    7|                 </div>
    8|             <% }) %>
    9|         <% } %>

C:\blog\satt\themes\cards\layout\_partial\post\post-entry.ejs:20
    18| <div class="post-entry__meta">
    19|     <%- partial('_meta/date') %>
 >> 20|     <%- partial('_meta/category') %>
    21| </div>
    22| <%- partial('_meta/tags') %>
    23| <a href="<%= url_for(post.link || post.path) %>" class="post-entry__link"><%= post.title || theme.meta.title %></a>

Partial _meta/category does not exist. (in _partial\post\post-entry.ejs)
    at Object.partial (C:\blog\satt\node_modules\hexo\lib\plugins\helper\partial.js:16:11)
    at eval (C:\blog\satt\themes\cards\layout\_partial\post\post-entry.ejs:41:17)
    at post-entry (C:\blog\satt\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\blog\satt\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\blog\satt\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\blog\satt\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\blog\satt\themes\cards\layout\_partial\post\post-list.ejs:19:17)
    at _Query.forEach (C:\blog\satt\node_modules\warehouse\lib\query.js:36:7)
    at eval (C:\blog\satt\themes\cards\layout\_partial\post\post-list.ejs:16:19)
    at post-list (C:\blog\satt\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\blog\satt\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\blog\satt\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\blog\satt\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\blog\satt\themes\cards\layout\index.ejs:12:17)
    at index (C:\blog\satt\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (C:\blog\satt\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\blog\satt\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\blog\satt\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\blog\satt\node_modules\bluebird\js\release\util.js:16:23)
    at C:\blog\satt\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\blog\satt\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)

如果用1.2.2版本则可以正常运行

**Comment by ChrAlpha** [comment]
一处 typo（#98）所致，已在 `1.3.1` 中修复。
