### ISSUE TITLE
报错是为什么呢（小白求问）

### ISSUE THREAD

**Issue by Three-Colors** [ChrAlpha/hexo-theme-cards#15]
Unhandled rejection TypeError: /Users/huang/MyBlog/themes/cards/layout/layout.ejs:9
    7|             <%- body %>
    8|         </div>
 >> 9|         <%- partial('_partial/scripts') %>
    10|     </body>
    11| </html>
    12|

/Users/huang/MyBlog/themes/cards/layout/_partial/scripts.ejs:1
 >> 1| <% if (config.lazyload.enable) { %>
    2|     <script defer crossorigin="anonymous" src="<%- theme.vendors.lazyload || 'https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.0/dist/lazyload.min.js' %>"></script>
    3|     <script>
    4|         window.lazyLoadOptions = {

Cannot read property 'enable' of undefined
    at eval (/Users/huang/MyBlog/themes/cards/layout/_partial/scripts.ejs:8:28)
    at scripts (/Users/huang/MyBlog/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiledSync (/Users/huang/MyBlog/node_modules/hexo/lib/theme/view.js:132:22)
    at viewFn.View.renderSync (/Users/huang/MyBlog/node_modules/hexo/lib/theme/view.js:60:23)
    at Object.partial (/Users/huang/MyBlog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/Users/huang/MyBlog/themes/cards/layout/layout.ejs:22:17)
    at layout (/Users/huang/MyBlog/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiled (/Users/huang/MyBlog/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/Users/huang/MyBlog/node_modules/hexo/lib/theme/view.js:41:15)
    at /Users/huang/MyBlog/node_modules/hexo/lib/theme/view.js:52:23
    at tryCatcher (/Users/huang/MyBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/huang/MyBlog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/huang/MyBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/huang/MyBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/huang/MyBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/huang/MyBlog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/huang/MyBlog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/huang/MyBlog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/huang/MyBlog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by Konghuaiqing** [comment]
这个是在什么流程时报错的？
比如cl , g , d

**Comment by Three-Colors** [comment]
就是我改好站点配置文件之后运行hexo s --debug的时候网站界面就无法显示（用hexo原主题不会报错），然后报这个错

**Comment by Konghuaiqing** [comment]
这是完整的错误嘛？

**Comment by Three-Colors** [comment]
嗯嗯，这个前面还有一句
10:04:16.202 ERROR Render HTML failed: index.html
其他地方都没有显示error

**Comment by Konghuaiqing** [comment]
你有hexo g嘛

**Comment by Konghuaiqing** [comment]
或者是hexo cl

**Comment by Three-Colors** [comment]
有hexo g

**Comment by Three-Colors** [comment]
应该hexo g还是不应该hexo g呀

**Comment by Konghuaiqing** [comment]
大概的流程是hexo cl && hexo g && hexo s

**Comment by Konghuaiqing** [comment]
或者发下你的主题配置文件

**Comment by Three-Colors** [comment]
可是一到hexo g就开始报错了，主题配置文件是指我从你们的仓库一起git clone下来的cards文件夹里的这个_config,yml嘛，可是我还没改过这个文件呀。
我只改了站点配置文件里的theme

**Comment by Konghuaiqing** [comment]
那就对了，很多东西要配置
留空应该会报错

**Comment by Three-Colors** [comment]
哦哦，我以为会像那个landscape一样有一个初始界面，那我先按照主题文档上写的配置一下吧，谢谢你

**Comment by Konghuaiqing** [comment]
嗯嗯，不客气，我也是刚入坑cards的小白，极力推荐哦

**Comment by Three-Colors** [comment]
可是我配置了之后也一样报错呀，真是太难了

**Comment by Konghuaiqing** [comment]
在？有qq嘛，找你具体交流下~

**Comment by Three-Colors** [comment]
1003004270，你加我吧

**Comment by Konghuaiqing** [comment]
请求发了~

**Comment by ChrAlpha** [comment]
疏忽，并非所有用户希望开启 lazyload，而判断开启方式不太合适，导致了如是报错。

已在 [`79ccbd5`](https://github.com/ChrAlpha/hexo-theme-cards/commit/79ccbd558d733472adf7f9b3234d379e9c3ef073) 尝试修复，请尝试获取最新 master 分支。
