### ISSUE TITLE
更新后valine自定义表情功能依旧无法使用

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#6]
$ hexo cl && hexo d
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Start processing
ERROR Process failed: _posts/Windows仿MacUI.md
YAMLException: duplicated mapping key at line 17, column -11:
    categories:
    ^
    at generateError (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at storeMappingPair (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:335:7)
    at readBlockMapping (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1098:9)
    at composeNode (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (G:\blog\node_modules\hexo-front-matter\lib\front_matter.js:80:21)
    at parse (G:\blog\node_modules\hexo-front-matter\lib\front_matter.js:56:12)
    at G:\blog\node_modules\hexo\lib\plugins\processor\post.js:48:20
    at tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog\node_modules\bluebird\js\release\promise.js:544:35)
    at Promise._settlePromise (G:\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\blog\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\blog\node_modules\bluebird\js\release\promise_array.js:145:14)
    at PromiseArray._iterate (G:\blog\node_modules\bluebird\js\release\promise_array.js:115:31)
    at PromiseArray.init [as _init] (G:\blog\node_modules\bluebird\js\release\promise_array.js:79:10)
    at Promise._settlePromise (G:\blog\node_modules\bluebird\js\release\promise.js:601:21)

报错信息如上
![image](https://user-images.githubusercontent.com/58429614/80586293-51ecb580-8a47-11ea-8a66-aca74c28b9f5.png)
更新后添加了自定义表情，没有实现效果
貌似连valine自身都无法显示了

**Comment by Konghuaiqing** [comment]
去valine官方群联系了作者
如下
![image](https://user-images.githubusercontent.com/58429614/80589169-464fbd80-8a4c-11ea-8ffb-57d49055e3df.png)
不太懂json解析
希望可以为你带来思路

**Comment by ChrAlpha** [comment]
json 编码是我疏忽了，但是从你的配置文件中还是看出点问题。

主题配置文件是 yaml 格式，所以不能使用这种带大括号的格式，而是使用缩进，例如：

```yaml
    emojiCDN: '//i0.hdslb.com/bfs/emote/'
    emojiMaps:
      tv_doge: 6ea59c827c414b4a2955fe79e0f6fd3dcd515e24.png
      tv_亲亲: a8111ad55953ef5e3be3327ef94eb4a39d535d06.png
      tv_偷笑: bb690d4107620f1c15cff29509db529a73aee261.png
      tv_再见: 180129b8ea851044ce71caf55cc8ce44bd4a4fc8.png
      tv_冷漠: b9cbc755c2b3ee43be07ca13de84e5b699a3f101.png
      tv_发怒: 34ba3cd204d5b05fec70ce08fa9fa0dd612409ff.png
      tv_发财: 34db290afd2963723c6eb3c4560667db7253a21a.png
      tv_可爱: 9e55fd9b500ac4b96613539f1ce2f9499e314ed9.png
      tv_吐血: 09dd16a7aa59b77baa1155d47484409624470c77.png
      tv_呆: fe1179ebaa191569b0d31cecafe7a2cd1c951c9d.png
      tv_呕吐: 9f996894a39e282ccf5e66856af49483f81870f3.png
      tv_困: 241ee304e44c0af029adceb294399391e4737ef2.png
      tv_坏笑: 1f0b87f731a671079842116e0991c91c2c88645a.png
      tv_大佬: 093c1e2c490161aca397afc45573c877cdead616.png
      tv_大哭: 23269aeb35f99daee28dda129676f6e9ea87934f.png
      tv_委屈: d04dba7b5465779e9755d2ab6f0a897b9b33bb77.png
      tv_害羞: a37683fb5642fa3ddfc7f4e5525fd13e42a2bdb1.png
      tv_尴尬: 7cfa62dafc59798a3d3fb262d421eeeff166cfa4.png
      tv_微笑: 70dc5c7b56f93eb61bddba11e28fb1d18fddcd4c.png
      tv_思考: 90cf159733e558137ed20aa04d09964436f618a1.png
      tv_惊吓: 0d15c7e2ee58e935adc6a7193ee042388adc22af.png
```

请获取最新版本后再次尝试，抱歉。

**Comment by Konghuaiqing** [comment]
收到，马上尝试

**Comment by Konghuaiqing** [comment]
感谢作者，经测试已成功
如下
![image](https://user-images.githubusercontent.com/58429614/80662697-7fc40f80-8ac4-11ea-9070-35b3d0dcb8c4.png)
但在生成的时候依旧报错
报错信息如下：
ERROR Process failed: _posts/Windows仿MacUI.md
YAMLException: duplicated mapping key at line 17, column -11:
    categories:
    ^
    at generateError (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at storeMappingPair (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:335:7)
    at readBlockMapping (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1098:9)
    at composeNode (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (G:\blog\node_modules\hexo-front-matter\lib\front_matter.js:80:21)
    at parse (G:\blog\node_modules\hexo-front-matter\lib\front_matter.js:56:12)
    at G:\blog\node_modules\hexo\lib\plugins\processor\post.js:48:20
    at tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog\node_modules\bluebird\js\release\promise.js:544:35)
    at Promise._settlePromise (G:\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\blog\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\blog\node_modules\bluebird\js\release\promise_array.js:145:14)
    at PromiseArray._iterate (G:\blog\node_modules\bluebird\js\release\promise_array.js:115:31)
    at PromiseArray.init [as _init] (G:\blog\node_modules\bluebird\js\release\promise_array.js:79:10)
    at Promise._settlePromise (G:\blog\node_modules\bluebird\js\release\promise.js:601:21)
不知道因为什么呢，希望作者可以帮我看看出了什么问题
谢谢~
PS：你的博客友链已加在我的博客中哦

**Comment by Konghuaiqing** [comment]
报错已解决，原因
文章中的 categories:
后面没有写内容
